const wordScrambleBank = {
  // 200 four-letter words — simple, kid-friendly
  level1: [
    "bark", "jump", "fish", "rain", "star", "frog", "cake", "leaf", "duck", "bear",
    "ball", "bird", "boat", "book", "bull", "bush", "camp", "card", "cart", "cave",
    "chip", "clam", "claw", "coat", "coin", "cold", "comb", "cook", "cool", "corn",
    "crab", "crow", "curl", "cute", "dark", "dart", "dash", "deer", "dish", "doll",
    "door", "dove", "down", "drag", "draw", "drip", "drop", "drum", "dust", "dusk",
    "feel", "feet", "fern", "fire", "flag", "flat", "flea", "flip", "flow", "foam",
    "fold", "food", "foot", "fork", "form", "fort", "fowl", "free", "full", "game",
    "gate", "glow", "glue", "goat", "gold", "good", "gust", "hack", "hail", "hare",
    "harp", "hawk", "haze", "head", "heal", "heap", "heat", "heel", "helm", "help",
    "herb", "herd", "hide", "hill", "hive", "hole", "home", "hood", "hook", "hoot",
    "horn", "hose", "host", "howl", "hull", "hump", "hunt", "iris", "jade", "jest",
    "jolt", "junk", "kale", "keen", "kelp", "kind", "king", "kite", "knee", "knit",
    "lace", "lake", "lamb", "lamp", "lane", "lark", "lash", "lava", "lawn", "lead",
    "lean", "leap", "lime", "line", "link", "lion", "list", "live", "load", "loaf",
    "lock", "loft", "lone", "long", "loon", "lump", "lung", "lynx", "mane", "mare",
    "mark", "mast", "maze", "meal", "meat", "melt", "mice", "mild", "milk", "mill",
    "mint", "mist", "moat", "mole", "moss", "moth", "mule", "musk", "nail", "nest",
    "newt", "nice", "nook", "nose", "oven", "palm", "park", "path", "pear", "peck",
    "peel", "pink", "plum", "pond", "pool", "pork", "port", "puff", "race", "rack",
    "reed", "reef", "rest", "rice", "ride", "ring", "road", "rock", "role", "rope",
  ],

  // 200 five-to-six-letter words — moderate difficulty
  level2: [
    "beach", "tiger", "cloud", "river", "pizza", "smile", "grape", "stone", "swing", "flame",
    "acorn", "algae", "amber", "angel", "apple", "arrow", "badge", "barge", "beech", "berry",
    "bison", "blade", "blast", "blaze", "bloom", "blown", "blunt", "blush", "board", "braid",
    "brake", "brave", "bread", "break", "breed", "brick", "bride", "brine", "brook", "broth",
    "brown", "brush", "bunch", "cabin", "camel", "candy", "cargo", "cedar", "chalk", "charm",
    "chart", "chase", "chick", "chirp", "chord", "chunk", "cider", "clamp", "clash", "clasp",
    "cliff", "climb", "clink", "cloak", "clock", "clone", "close", "cloth", "clout", "clown",
    "cluck", "cobra", "comet", "coral", "couch", "cough", "court", "cover", "craft", "crane",
    "crash", "creak", "creek", "crisp", "croak", "crook", "cross", "crowd", "crumb", "crush",
    "crust", "daisy", "dance", "dingo", "dizzy", "dodge", "draft", "drain", "drift", "drink",
    "drive", "drone", "drown", "dwarf", "eagle", "earth", "ember", "extra", "fable", "fairy",
    "fancy", "feast", "field", "finch", "flake", "flare", "flash", "flask", "flick", "fling",
    "float", "flock", "floor", "flour", "flute", "force", "forge", "frost", "fruit", "gauze",
    "gecko", "ghost", "girth", "glass", "gleam", "glide", "glint", "gloom", "glory", "gloss",
    "glove", "gnome", "goose", "gourd", "grace", "grain", "grand", "grant", "grasp", "graze",
    "green", "grief", "grill", "grind", "groan", "groom", "growl", "gruff", "guava", "guard",
    "guild", "guile", "hatch", "heron", "holly", "honey", "horse", "house", "hover", "hyena",
    "igloo", "jaunt", "joust", "juice", "knack", "koala", "lance", "laser", "latch", "leech",
    "lemon", "llama", "lodge", "lotus", "lunch", "maple", "march", "marsh", "melon", "moose",
    "mouse", "mulch", "music", "ocean", "olive", "onion", "otter", "ounce", "outer", "panda",
  ],

  // 200 seven-to-nine-letter words — challenging
  level3: [
    "dolphin", "rainbow", "lantern", "blanket", "chicken", "feather", "penguin", "thunder", "volcano", "compass",
    "academy", "airport", "almanac", "ancient", "archway", "auction", "balance", "balloon", "bandana", "barrier",
    "bassoon", "bathtub", "battery", "beneath", "bicycle", "blossom", "bouquet", "bowling", "bracket", "bravery",
    "breadth", "brewery", "buffalo", "cabinet", "captain", "capture", "cascade", "catfish", "century", "channel",
    "chapter", "cheetah", "chimney", "cinnamon", "citadel", "clarity", "classic", "coconut", "combine", "canteen",
    "connect", "contend", "cookout", "correct", "cottage", "counsel", "country", "courage", "cricket", "crystal",
    "culture", "cunning", "curtain", "cushion", "cyclone", "dancing", "darling", "daylight", "defense", "delight",
    "deliver", "destiny", "diamond", "distant", "draught", "dreamer", "dribble", "drummer", "eastern", "eclipse",
    "elegant", "element", "emperor", "enchant", "enforce", "essence", "evening", "evident", "exhaust", "explain",
    "express", "extreme", "factory", "farming", "festive", "fiction", "finding", "firefly", "fitness", "flavors",
    "flowers", "fluency", "flutter", "foghorn", "forbear", "forgive", "fortify", "forward", "fossils", "freedom",
    "galleon", "garland", "gateway", "genuine", "giraffe", "glacier", "glimmer", "glisten", "glowing", "gorilla",
    "granite", "grapple", "gravity", "gymnast", "halibut", "harmony", "harvest", "haunted", "helpful", "herring",
    "history", "honesty", "horizon", "hostile", "humming", "hunting", "iceberg", "imagine", "improve", "include",
    "inspire", "instant", "intense", "jasmine", "journey", "justice", "kingdom", "kitchen", "knowing", "lullaby",
    "machine", "mammoth", "mansion", "meadows", "measure", "monster", "morning", "mystery", "nesting", "network",
    "nothing", "nursery", "nourish", "octopus", "onwards", "orchard", "outdoor", "package", "painter", "panther",
    "pattern", "peacock", "pebbles", "perfect", "pilgrim", "pioneer", "piranha", "pitcher", "plunder", "problem",
    "rooster", "sailing", "sardine", "sawdust", "scarlet", "science", "seafood", "seagull", "season", "servant",
    "shelter", "silence", "skating", "skipper", "skylark", "sparrow", "spinach", "sponge", "spotted", "squeeze",
  ],
};

export default wordScrambleBank;
